### ISSUE TITLE
README and related tasks

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#569]
# Tasks

- [x] Create custom logo for the project with the text ```GirlScript Website Boilerplate```(Please do not use Canva 🙏)

- [x] Remove the Contribution guidelines from README and Update the [Contributing.MD](https://github.com/smaranjitghose/girlscript_chennai_website/blob/master/CONTRIBUTING.md) 

        -  Use Relevant GIFs (from GIPHY) or Images (from Unsplash) to make it interactive
        -  Use HTML in the file to properly align the content
        -  Modify the content to make it more beginner friendly (if required)

- [x] Improve the ```Geeks behind this section``` . For reference see [this](https://github.com/vinitshahdeo/Water-Monitoring-System/blob/master/README.md)

- [x] Add a ```Getting_Started.MD``` file and give atleast 3 resources
  
      -  Do your research for this one. 
      - Checkout various awesome-resources repositories on GitHub, web dev blogs, YouTube channels (like Brad Traversy, DevEd), freecodecamp. 
      - Please add the resources judiciously with proper headings.
      - Any random additions will not be merged 
      - Suggested Topics are: HTML5, CSS3 (Basics, Flexbox, Grid). Mobile Responsiveness, Javascript Basics , ES6, Git, GitHub Markdown
      - Add tips and tricks for each
      - Add links and gifs to some nice hover effects,etc ( Surf Codepen.io for this)
      - Add resources for Hosting from GitHub pages,Netlify etc

# Guidelines for the issue:

- Comment down below for which task you want to take up. Don't simply write ```i want to work on this``` or ```assign me this``` or ```interested```

- If you want to do something additional (that is not mentioned above), feel free to comment below, the mentors will approve if found useful

**Comment by Adyasha8105** [comment]
@smaranjitghose I will work on the first issue.

**Comment by Aman-Codes** [comment]
@smaranjitghose I would like to work on the first task.
* Remove the Contribution guidelines from README and Update the Contributing.MD

**Comment by Adyasha8105** [comment]
@smaranjitghose I wan to work on the logo part.

**Comment by smaranjitghose** [comment]
@Aman-Codes Are you working on the Getting Started.MD or the ```Geeks behind this section```?

**Comment by Aman-Codes** [comment]
@smaranjitghose I would like to take up another issue next time.

**Comment by Adyasha8105** [comment]
@smaranjitghose I will work on the third issue.

**Comment by shreyakapoor08** [comment]
Can I work on it ?

**Comment by smaranjitghose** [comment]
> Can I work on it ?

Take up the ```Getting_Started.MD``` part

**Comment by smaranjitghose** [comment]
@shreyakapoor08  for the Getting Started, give the rest of the work as a single PR please

**Comment by smaranjitghose** [comment]
@Adyasha8105 any updates on your assigned part?

**Comment by smaranjitghose** [comment]
> @Adyasha8105 any updates on your assigned part?

Try to align my and @anushbhatia 's pictures side by side

**Comment by anushbhatia** [comment]
Also u can add this 
  [![hi](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start/deploy?repository=https://github.com/netlify/netlify-photo-gallery)
prefered would be make a custom one

**Comment by smaranjitghose** [comment]
> > @Adyasha8105 any updates on your assigned part?
> 
> Try to align my and @anushbhatia 's pictures side by side

@Adyasha8105 can you please follow the reference I gave above and try to replicate the same. Also, add @anushbhatia 's suggestion above

**Comment by smaranjitghose** [comment]
> > > @Adyasha8105 any updates on your assigned part?
> > 
> > 
> > Try to align my and @anushbhatia 's pictures side by side
> 
> @Adyasha8105 can you please follow the reference I gave above and try to replicate the same. Also, add @anushbhatia 's suggestion above

@Adyasha8105 are you still working on this?

**Comment by Adyasha8105** [comment]
@smaranjitghose I think this task is now over.

**Comment by smaranjitghose** [comment]
> @smaranjitghose I think this task is now over.

@Adyasha8105 can you please put my and Anush's card one after the other and centre align them as in the current readme it's looking a bit unappealing
